---
- name: Install iSCSI initiator utils
  ansible.builtin.dnf:
    name:
      - iscsi-initiator-utils
      - device-mapper-multipath
    state: present

- name: Enable and start iscsid service
  ansible.builtin.systemd:
    name:    iscsid
    enabled: true
    state:   started
