# ======================================================================
#  Vagrant Static Inventory – Oracle RAC Lab
# ======================================================================

[storage]
storage1  ansible_host=192.168.56.200

[racnodes]
racnode1  ansible_host=192.168.56.101
racnode2  ansible_host=192.168.56.102

# ── 논리 그룹 ──────────────────────────────────────────────────────────
[rac_cluster:children]
racnodes

[lab:children]
storage
racnodes
