---
# 커널 파라미터 설정 (/etc/sysctl.d/97-oracle-rac.conf)

- name: Deploy Oracle RAC sysctl config
  ansible.builtin.template:
    src:   sysctl_oracle.j2
    dest:  /etc/sysctl.d/97-oracle-rac.conf
    owner: root
    group: root
    mode:  "0644"
  notify: Apply sysctl

- name: Apply sysctl parameters immediately
  ansible.builtin.command: sysctl --system
  changed_when: false
